Repository LEQO-Framework/leqo-backend, pull requests merged in 2025-02, with the labels that each got.

#3 Add basic pipeline
  .github/workflows/ci.yml
  .gitignore
  app/hello.py
  pyproject.toml
  uv.lock
Labels: area::pipeline

#7 chore: minimal changes to gitignore
  .gitignore
Labels: area::project-structure

#6 build: add docker integration
  Dockerfile
  README.md
  docker-compose.yaml
Labels: area::deploy

#11 docs: update README
  README.md
Labels: area::documentation

#13 fix: pull_request_template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area::documentation

#16 Build docker image in ci
  .github/workflows/docker.yml
  README.md
  compose-dev.yaml
  compose.yaml
Labels: area::deploy

#21 Setup pytest for testing
  .github/workflows/ci.yml
  docs/index.rst
  docs/testing.rst
  pyproject.toml
  tests/__init__.py
  tests/manual.http
  tests/other/test_openqasm_spec.py
  uv.lock
Labels: area::testing

#25 Freeze lockfile in ci
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: area::pipeline
