Repository LEQO-Framework/leqo-backend, pull requests merged in 2025-04, with the labels that each got.

#60 refactor: merging interface
  app/processing/__init__.py
  app/processing/graph.py
  app/processing/pre/renaming.py
  app/utils.py
  pyproject.toml
  tests/processing/pre/test_renaming.py
  tests/processing/test_init.py
  uv.lock
Labels: area::project-structure

#62 Fix: index parse handle empty
  app/processing/utils.py
  tests/processing/test_utils.py
Labels: hotfix

#65 feat: Inline integer `const`s
  app/processing/pre/__init__.py
  app/processing/pre/inlining.py
  tests/processing/pre/test_inlining.py
Labels: area:core

#77 docs: Add some documentation to the model modules
  app/model/CompileRequest.py
  app/model/StatusBody.py
Labels: area::documentation

#22 feat: add QASM 2.x to QASM 3.0 converter
  app/converter/__init__.py
  app/converter/qasm_converter.py
  app/converter/qasm_lib/qasm3_qelib1.qasm
  docs/code/app.converter.rst
  docs/code/app.model.rst
  docs/code/app.rst
  docs/index.rst
  pyproject.toml
  tests/test_converter.py
Labels: area:core

#66 feat: Sort Imports (post)
  app/processing/post/__init__.py
  app/processing/post/sort_imports.py
  app/processing/utils.py
  tests/processing/post/__init__.py
  tests/processing/post/test_sort_imports.py
Labels: area:core

#63 docs: Use autoapi
  app/__init__.py
  app/main.py
  app/model/__init__.py
  app/openqasm3/__init__.py
  app/openqasm3/ast.py
  app/openqasm3/parser.py
  app/openqasm3/printer.py
  app/processing/__init__.py
  app/processing/graph.py
  app/processing/pre/__init__.py
  app/processing/pre/renaming.py
  app/processing/utils.py
  app/utils.py
  docs/code/app.converter.rst
  docs/code/app.model.rst
  docs/code/app.openqasm3.rst
  docs/code/app.processing.post.rst
  docs/code/app.processing.pre.rst
  docs/code/app.processing.rst
  docs/code/app.rst
  docs/conf.py
  docs/index.rst
  docs/openqasm3.rst
  docs/openqasm3/ast.rst
  docs/openqasm3/visitor.rst
  pyproject.toml
  uv.lock
Labels: area::documentation

#64 feat: Parse io annotation
  app/processing/graph.py
  app/processing/pre/__init__.py
  app/processing/pre/io_parser.py
  app/processing/utils.py
  tests/processing/pre/test_io_parse.py
  tests/processing/test_utils.py
Labels: area:core

#80 refactor: extract merge submodule
  app/processing/__init__.py
  app/processing/merge/__init__.py
  tests/processing/merge/__init__.py
  tests/processing/merge/test_init.py
Labels: area::project-structure

#82 feat: connect qubits
  app/processing/merge/connections.py
  tests/processing/merge/test_connections.py
Labels: area:core

#75 feat: Modify converter to optionally handle qasm3
  app/converter/__init__.py
  app/converter/qasm_converter.py
  app/openqasm3/parser.py
  tests/processing/merge/test_init.py
  tests/test_converter.py
Labels: area:core

#46 docs: io annotation spec
  docs/conf.py
  docs/index.rst
  docs/usage/annotations.rst
  openqasm3_lexer/__init__.py
  pyproject.toml
  uv.lock
Labels: area::documentation

#92 fix: `LeqoPrinter`
  app/openqasm3/printer.py
  app/processing/__init__.py
  tests/openqasm3/test_printer.py
  tests/processing/merge/test_init.py
Labels: area:core

#89 feat: requirements for optimization
  app/processing/graph.py
  app/processing/merge/connections.py
  app/processing/optimize/__init__.py
  app/processing/pre/io_parser.py
  tests/processing/merge/test_connections.py
  tests/processing/pre/test_io_parse.py
Labels: area:core

#102 chore: Gather code coverage
  .github/workflows/ci.yml
  .gitignore
  pyproject.toml
  uv.lock
Labels: area::testing

#108 feat: rename with prefix
  app/processing/pre/renaming.py
  tests/processing/merge/test_init.py
  tests/processing/pre/test_renaming.py
Labels: area:core

#94 feat: add dto specification
  app/model/CompileRequest.py
Labels: area:core

#86 feat: add enricher setup
  .env.template
  .gitignore
  README.md
  app/enricher/engine.py
  app/enricher/models.py
  compose-dev.yaml
  compose.yaml
  pyproject.toml
  uv.lock
Labels: area:core
