Repository LEQO-Framework/leqo-backend, pull requests merged in 2025-05, with the labels that each got.

#133 refactor: use leqo data model
  app/enricher/__init__.py
  app/model/data_types.py
  app/processing/graph.py
  app/processing/merge/connections.py
  app/processing/pre/io_parser.py
  app/processing/size_casting.py
  app/utils.py
  tests/processing/merge/test_connections.py
  tests/processing/pre/test_io_parse.py
  tests/processing/test_size_casting.py
Labels: area:core

#127 feat: enricher for trivial nodes
  app/enricher/__init__.py
  app/enricher/literals.py
  app/enricher/measure.py
  app/enricher/utils.py
  app/utils.py
  tests/enricher/test_literals.py
  tests/enricher/test_measure.py
  tests/test_utils.py
Labels: area:core

#147 docs: correct typo in enricher docs
  app/enricher/__init__.py
Labels: area::documentation

#132 feat: enrich graph
  app/main.py
  app/processing/__init__.py
  app/utils.py
Labels: area:core

#93 docs: dirty ancilla & uncompute spec
  docs/conf.py
  docs/usage/annotations.rst
Labels: area::documentation

#153 feat: enricher strategy may return multiple results
  app/enricher/__init__.py
  app/enricher/literals.py
  app/enricher/measure.py
  app/enricher/merger.py
  app/enricher/splitter.py
  tests/enricher/test_init.py
  tests/enricher/test_literals.py
  tests/enricher/test_measure.py
  tests/enricher/test_merger.py
  tests/enricher/test_splitter.py
Labels: area:core

#157 feat: dto for nested nodes
  app/model/CompileRequest.py
Labels: area:core

#161 fix: no duplicate postprocess
  app/processing/merge/__init__.py
Labels: area:core

#170 feat: qubit output for measure node
  app/enricher/measure.py
  tests/enricher/test_measure.py
Labels: area::enricher

#171 fix: tests on main
  tests/baselines/debug/compile/addition.yml
  tests/baselines/debug/compile/merger_splitter.yml
Labels: area::testing, hotfix

#148 feat(enricher): add database enrich strategy
  app/enricher/__init__.py
  app/enricher/db_enricher.py
  app/enricher/encode_value.py
  app/enricher/engine.py
  app/enricher/models.py
  app/enricher/operator.py
  app/enricher/prepare_state.py
  app/main.py
  app/services.py
  pyproject.toml
  tests/baselines/test_main.py
  tests/conftest.py
  tests/enricher/test_encode_value.py
  tests/enricher/test_operator.py
  tests/enricher/test_prepare_state.py
  uv.lock
Labels: area::enricher

#176 feat(enricher): enrich gates
  app/enricher/gates.py
  app/services.py
  tests/baselines/debug/compile/gates-broadcasting.yml
  tests/baselines/debug/compile/gates.yml
  tests/enricher/test_gates.py
Labels: area::enricher

#181 refactor: model to model transformation
  app/model/CompileRequest.py
  app/processing/__init__.py
  app/processing/converted_graph.py
Labels: area:core

#184 fix: deterministic output
  app/processing/__init__.py
  app/processing/converted_graph.py
  app/processing/graph.py
  app/services.py
  tests/baselines/debug/compile/addition.yml
  tests/baselines/debug/compile/gates-broadcasting.yml
  tests/baselines/debug/compile/gates.yml
  tests/baselines/debug/compile/literals.yml
  tests/baselines/debug/compile/malicious_node_id.yml
  tests/baselines/debug/compile/merger_splitter.yml
  tests/baselines/debug/compile/size_cast.yml
  tests/baselines/test_main.py
Labels: area:core

#182 feat: enrich additional gates
  app/enricher/gates.py
  app/model/CompileRequest.py
  app/openqasm3/stdgates.py
Labels: area::enricher
