Repository LEQO-Framework/leqo-backend, pull requests merged in 2025-03, with the labels that each got.

#28 docs: Sphinx Cross-references
  docs/conf.py
  docs/example-cross-references.rst
  docs/index.rst
  pyproject.toml
  uv.lock
Labels: area::documentation

#29 Added openqasm3[parser] as dependency
  pyproject.toml
  uv.lock
Labels: hotfix

#26 [Preprocessing] Renaming
  .github/workflows/docs.yml
  app/model/SectionInfo.py
  app/preprocessing/__init__.py
  app/preprocessing/renaming.py
  app/preprocessing/utils.py
  docs/index.rst
  docs/openqasm3/ast.rst
  docs/openqasm3/visitor.rst
  docs/preprocessing.rst
  tests/preprocessing/__init__.py
  tests/preprocessing/test_renaming.py
  tests/preprocessing/utils.py
Labels: area:core

#39 fix: autodoc module resolution
  docs/conf.py
Labels: area::documentation

#45 feat: Parse io annotation
  app/preprocessing/utils.py
  docs/preprocessing.rst
  tests/preprocessing/test_utils.py
Labels: area:core

#49 refactor: Unified compile interface
  app/model/SectionInfo.py
  app/openqasm3/__init__.py
  app/openqasm3/ast.py
  app/openqasm3/parser.py
  app/openqasm3/printer.py
  app/preprocessing/__init__.py
  app/processing/__init__.py
  app/processing/graph.py
  app/processing/post/__init__.py
  app/processing/pre/__init__.py
  app/processing/pre/renaming.py
  app/processing/utils.py
  docs/index.rst
  docs/processing/pre.rst
  tests/openqasm3/test_openqasm_spec.py
  tests/processing/__init__.py
  tests/processing/pre/__init__.py
  tests/processing/pre/test_renaming.py
  tests/processing/test_init.py
  tests/processing/test_utils.py
  tests/processing/utils.py
Labels: area:core

#32 fix: Upstream `QASMTransformer`
  app/openqasm3/visitor.py
  app/processing/utils.py
  tests/openqasm3/__init__.py
  tests/openqasm3/test_visitor.py
Labels: area:core
